[package]
name = "msp432-newio"
version = "0.1.0"
authors = ["Pramode <mail@pramode.in>"]
edition = "2018"

[dependencies]
msp432p401r-pac = "0.1.0"
cortex-m = "0.7.1"
cortex-m-rt = "0.6.11"
panic-abort = "0.3.2"

[profile.release]
debug = true
lto = true
